### ISSUE TITLE
Failure with websocket

### ISSUE THREAD

**Issue by cnlpete** [crossbario/autobahn-js#214]
Wehn trying the latest version, i get the following error message:

```
.../node_modules/autobahn/lib/transport/websocket.js:108
            var serializer_part = websocket.protocol.split('.')[2];
                                                    ^

TypeError: Cannot read property 'split' of undefined
    at WebSocket.<anonymous> (.../node_modules/autobahn/lib/transport/websocket.js:108:53)
    at emitNone (events.js:67:13)
    at WebSocket.emit (events.js:166:7)
    at WebSocket.establishConnection (.../node_modules/autobahn/node_modules/ws/lib/WebSocket.js:887:8)
    at ClientRequest.upgrade (.../node_modules/autobahn/node_modules/ws/lib/WebSocket.js:778:25)
    at ClientRequest.g (events.js:260:16)
    at emitThree (events.js:97:13)
    at ClientRequest.emit (events.js:175:7)
    at Socket.socketOnData (_http_client.js:341:11)
    at emitOne (events.js:77:13)
```

 ws version is `1.1.0` and autobahn `0.10.1`

**Comment by goeddea** [comment]
Just tried our basic nodejs template which comes with Crossbar.io and things are working. 

What is your setup that produces this error?

**Comment by oberstet** [comment]
No user response, works for me, closing.
