### ISSUE TITLE
TypeError: Cannot read property 'mask' of undefined

### ISSUE THREAD

**Issue by koxu1996** [crossbario/autobahn-js#264]
Hello,
today I tried running autobahn-js on my server and I got error:
```
2017-03-18T09:25:32+0100 [Guest        9892] /home/andrew/crossbar/node_modules/ws/lib/Sender.js:211
2017-03-18T09:25:32+0100 [Guest        9892] bufferUtil.mask(data, mask, outputBuffer, dataOffset, dataLength);
2017-03-18T09:25:32+0100 [Guest        9892] ^
2017-03-18T09:25:32+0100 [Guest        9892] TypeError: Cannot read property 'mask' of undefined
2017-03-18T09:25:32+0100 [Guest        9892] at Sender.frameAndSend (/home/andrew/crossbar/node_modules/ws/lib/Sender.js:211:17)
2017-03-18T09:25:32+0100 [Guest        9892] at /home/andrew/crossbar/node_modules/ws/lib/Sender.js:119:12
2017-03-18T09:25:32+0100 [Guest        9892] at Sender.flush (/home/andrew/crossbar/node_modules/ws/lib/Sender.js:265:33)
2017-03-18T09:25:32+0100 [Guest        9892] at Sender.send (/home/andrew/crossbar/node_modules/ws/lib/Sender.js:135:8)
2017-03-18T09:25:32+0100 [Guest        9892] at WebSocket.send (/home/andrew/crossbar/node_modules/ws/lib/WebSocket.js:267:18)
2017-03-18T09:25:32+0100 [Guest        9892] at Object.transport.send (/home/andrew/crossbar/node_modules/autobahn/lib/transport/websocket.js:100:23)
2017-03-18T09:25:32+0100 [Guest        9892] at Session.self._send_wamp (/home/andrew/crossbar/node_modules/autobahn/lib/session.js:283:20)
2017-03-18T09:25:32+0100 [Guest        9892] at Session.join (/home/andrew/crossbar/node_modules/autobahn/lib/session.js:1163:9)
2017-03-18T09:25:32+0100 [Guest        9892] at Object.self._transport.onopen (/home/andrew/crossbar/node_modules/autobahn/lib/connection.js:311:24)
2017-03-18T09:25:32+0100 [Guest        9892] at WebSocket.<anonymous> (/home/andrew/crossbar/node_modules/autobahn/lib/transport/websocket.js:118:23)
```
This is probably related to https://github.com/websockets/ws/issues/1040 and is fixed in `ws@^1.1.3`. Could you update `ws` version in package.json?

**Comment by koxu1996** [comment]
I was trying `npm update` but it didn't help. After I removed `node_modules` and executed `npm install` then `ws` was updated to `2.2.1 ` and error disappeard.
