### ISSUE TITLE
ws 3.0 breaks autobahn

### ISSUE THREAD

**Issue by sese** [crossbario/autobahn-js#299]
After websocket  released the ws:3.0.0 version autobahn use it as dependency and our crossbar application failed to start. I got this errors:

```
 /home/sese/app/node_modules/autobahn/lib/transport/websocket.js:99
 if (flags.binary) {
 ^
 TypeError: Cannot read property 'binary' of undefined
 at WebSocket.<anonymous> (/home/sese/app/node_modules/autobahn/lib/transport/websocket.js:99:22)
 at emitOne (events.js:96:13)
 at WebSocket.emit (events.js:188:7)
 at Receiver._receiver.onmessage (/home/sese/app/node_modules/ws/lib/WebSocket.js:146:47)
 at Receiver.dataMessage (/home/sese/app/node_modules/ws/lib/Receiver.js:389:14)
 at Receiver.getData (/home/sese/app/node_modules/ws/lib/Receiver.js:330:12)
 at Receiver.startLoop (/home/sese/app/node_modules/ws/lib/Receiver.js:165:16)
 at Receiver.add (/home/sese/app/node_modules/ws/lib/Receiver.js:139:10)
 at Socket._ultron.on (/home/sese/app/node_modules/ws/lib/WebSocket.js:142:22)
 at emitOne (events.js:96:13)
 at Socket.emit (events.js:188:7)
 at readableAddChunk (_stream_readable.js:176:18)
 at Socket.Readable.push (_stream_readable.js:134:10)
 at TCP.onread (net.js:551:20)
 Guest worker-002 exited with error A process has ended with a probable error condition: process ended with exit code 1.
```

And this error points to websocket.js:99:
```
websocket.on('message', function (data, flags) {
    if (flags.binary) {
        // FIXME!
    } else {  
        var msg = JSON.parse(data);
        transport.onmessage(msg);
    }
});
```

I suppose there is some unfinished code. We spent more than 6 hours, 4 developers to find something wrong in our application, we rollback commits from 3 repositories until we found this unexpected versioning issue. Please fix.

**Comment by oberstet** [comment]
AutobahnJS runs on both ws 1.x and 2.x_

* https://github.com/crossbario/autobahn-js/#nodejs-development
* https://github.com/crossbario/autobahn-js/blob/master/package.json#L19

Apparently, ws 3.0 was published just a day ago - maybe this breaks AB JS .. needs investigation. PRs are welcome!

**Comment by lpinca** [comment]
I think this is an issue only for `autobahn@<=0.9.9`. The [`flags`](https://github.com/crossbario/autobahn-js/blob/a3998f5e249a68f4dc1b16b0d32552826a6459d9/package/lib/transport/websocket.js#L121) argument which is gone in `ws@3` seems to be no longer used in `autobahn@>0.9.9`.

**Comment by oberstet** [comment]
works for me with current release:

```console
event: args= [ 'hello subscriber!', 5 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
closing ..
✔ testPubsubMultipleMatchingSubs

OK: 33 assertions (18127ms)
npm list ws bufferutil when crypto-js
autobahn@17.5.2 /home/oberstet/scm/crossbario/autobahn-js
├── bufferutil@3.0.0 
├── crypto-js@3.1.8 
├── when@3.7.8 
└── ws@3.0.0 

oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-js$ 
```
