### ISSUE TITLE
Subscription ID sent as float for unsubscribe()

### ISSUE THREAD

**Issue by agronholm** [crossbario/autobahn-js#329]
Our front-end developer reported that after an unsubscribe call the connection was lost. I looked at Crossbar's logs and found the following:
```
Nov 21 13:58:49 devib crossbar[1223]: 2017-11-21T13:58:49+0000 [Router         17] dropping connection to peer tcp4:172.17.0.1:57932 with abort=True: I dropped the WebSocket TCP connection: WAMP Protocol Error ('subscription' in UNSUBSCRIBE: invalid type <class 'float'> for ID)
```
This happend with msgpack. Wasn't this supposed to be fixed already?

**Comment by oberstet** [comment]
yes, I also think this was fixed. mmh. needs investigation ..

**Comment by agronholm** [comment]
No special mangling is done in the code for subscription IDs. I've started looking into the viability of msgpack5 but it does not pass one of the tests (decodes 1.7 incorrectly somehow). I will keep looking.

**Comment by agronholm** [comment]
As this does not apparently have anything to do with session IDs, I've updated the title accordingly.

**Comment by agronholm** [comment]
We've experimented with replacing msgpack-lite with msgpack5 and it eliminates this problem. I am now investigating the reason for the one test failure. If this is resolved, I will make a PR that replaces msgpack-lite with msgpack5.

**Comment by agronholm** [comment]
It was just a matter of setting one specific option. I've created #330 to fix this.

**Comment by oberstet** [comment]
Fixed via https://github.com/crossbario/autobahn-js/pull/330

**Comment by lajosbencz** [comment]
Encountered the error today:

```2019-01-25T13:14:34+0100 [Router       7284] Traceback (most recent call last):
  File "/home/lazos/.local/lib/python3.5/site-packages/autobahn/wamp/websocket.py                                                                                ", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/home/lazos/.local/lib/python3.5/site-packages/autobahn/wamp/serializer.p                                                                                y", line 135, in unserialize
    msg = Klass.parse(raw_msg)
  File "/home/lazos/.local/lib/python3.5/site-packages/autobahn/wamp/message.py",                                                                                 line 3759, in parse
    registration = check_or_raise_id(wmsg[2], u"'registration' in UNREGISTER")
  File "/home/lazos/.local/lib/python3.5/site-packages/autobahn/wamp/message.py",                                                                                 line 252, in check_or_raise_id
    raise ProtocolError(u"{0}: invalid type {1} for ID".format(message, type(valu                                                                                e)))
autobahn.wamp.exception.ProtocolError: 'registration' in UNREGISTER: invalid type                                                                                 <class 'float'> for ID
```

Versions:

```
 Crossbar.io        : 19.1.2
   txaio            : 18.8.1
   Autobahn         : 19.1.1
   Twisted          : 18.9.0-EPollReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 3.5.2/CPython
 Frozen executable  : no
 Operating system   : Linux-4.4.0-131-generic-x86_64-with-Ubuntu-16.04-xenial
 Host machine       : x86_64
```

No error with json transport protocol, only with msgpack
