### ISSUE TITLE
Cannot install autobahn-js on Microsoft Windows [Version 10.0.17134.48] (home)

### ISSUE THREAD

**Issue by ilovetogetspamed** [crossbario/autobahn-js#353]
```
c:\users\*********\downloads> pip install js.autobahn-0.9.2-2.zip
Processing c:\users\*********\downloads\js.autobahn-0.9.2-2.zip
Could not install packages due to an EnvironmentError: [Errno 22] invalid mode ('wb') or filename: 'c:\\users\\********\\appdata\\local\\temp\\pip-req-build-0cjwq5\\js/autobahn/test_autobahn|js.txt'
```
Tried in venv (created in PyCharm 2018.1) and with native Python 2.7.13 install.

Traceback from native attempt follows:

```
C:\Users\********\Downloads>pip install js.autobahn-0.9.2-2.zip
Processing c:\users\********\downloads\js.autobahn-0.9.2-2.zip
Exception:
Traceback (most recent call last):
  File "c:\users\********\.platformio\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\********\.platformio\python27\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\********\.platformio\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\********\.platformio\python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\users\********\.platformio\python27\lib\site-packages\pip\download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "c:\users\********\.platformio\python27\lib\site-packages\pip\download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "c:\users\********\.platformio\python27\lib\site-packages\pip\utils\__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "c:\users\********\.platformio\python27\lib\site-packages\pip\utils\__init__.py", line 499, in unzip_file
    fp = open(fn, 'wb')
IOError: [Errno 22] invalid mode ('wb') or filename: 'c:\\users\\********\\appdata\\local\\temp\\pip-sfz3i7-build\\js/autobahn/test_autobahn|js.txt'
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by oberstet** [comment]
https://github.com/crossbario/autobahn-js#get-it
