### ISSUE TITLE
Error message in browser console

### ISSUE THREAD

**Issue by markope** [crossbario/autobahn-js#355]
We constantly get this error message in the browser ( Chrome Version 66.0.3359.181 and other browsers too).
We have no way to deterministically reproduce the error and are also unsure about the harm it does.

```
Uncaught DOMException: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1002 is neither.
    at Object.f.close (http://localhost:8085/bower_components/autobahn/autobahn.min.js:3420:17)
    at A.r._protocol_violation (http://localhost:8085/bower_components/autobahn/autobahn.min.js:2279:23)
    at Object.A.r._process_EVENT (http://localhost:8085/bower_components/autobahn/autobahn.min.js:2386:22)
    at Object.A.r._socket.onmessage (http://localhost:8085/bower_components/autobahn/autobahn.min.js:2519:64)
    at WebSocket.d.onmessage (http://localhost:8085/bower_components/autobahn/autobahn.min.js:3385:17)
```

Will also post the error with the non minified version of autobahn-js as soon as I get it.

**Comment by oberstet** [comment]
1002 once was a valid close code, until the spec changed. anyways, yes, we should use another close code.

however, this specific error here is actually triggered from a protocol violation (see the log lines), and hence, after fixing the close code, you will simply uncover the actual root cause ..

**Comment by markope** [comment]
ok, so here is the browser console log output with non minified autobahn: 

```
autobahn.js:1 Uncaught DOMException: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1002 is neither.
    at Object.transport.close (https://localhost:8445/bower_components/autobahn/autobahn.js:1:88897)
    at Session.self._protocol_violation (https://localhost:8445/bower_components/autobahn/autobahn.js:1:51449)
    at Object.Session.self._process_EVENT (https://localhost:8445/bower_components/autobahn/autobahn.js:1:55529)
    at Object.Session.self._socket.onmessage (https://localhost:8445/bower_components/autobahn/autobahn.js:1:63078)
    at WebSocket.websocket.onmessage (https://localhost:8445/bower_components/autobahn/autobahn.js:1:88235)
transport.close @ autobahn.js:1
Session.self._protocol_violation @ autobahn.js:1
Session.self._process_EVENT @ autobahn.js:1
Session.self._socket.onmessage @ autobahn.js:1
websocket.onmessage @ autobahn.js:1
```

**Comment by oberstet** [comment]
We should use a WebSocket close code from the custom range for WAMP protocol violations, as 1002 ("protocol violation") is meant for WebSocket protocol errors

> note: this was a late change to the websocket spec ..
