### ISSUE TITLE
testPubsubMultipleMatchingSubs is broken

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-js#383]
Attached failure result. It does not seem to be a recent regression as I was able to reproduce it with a revert  back to few weeks.

```
om26er@Intel-NUC:~/code/crossbario/autobahn-js$ npm test -- test/test.js -t testPubsubMultipleMatchingSubs

> autobahn@18.3.2 test /home/om26er/code/crossbario/autobahn-js
> nodeunit test/test.js "test/test.js" "-t" "testPubsubMultipleMatchingSubs"


test.js
(node:6089) TimeoutOverflowWarning: 10000000000000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:6089) TimeoutOverflowWarning: 10000000000000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:6089) TimeoutOverflowWarning: 10000000000000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:6089) TimeoutOverflowWarning: 10000000000000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:6089) TimeoutOverflowWarning: 10000000000000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
all sessions connected
all test sessions subscribed!
session_ident=B subscribed with topic=com..topic1, match=wildcard
session_ident=C subscribed with topic=com.myapp, match=prefix
session_ident=D subscribed with topic=com, match=prefix
session_ident=E subscribed with topic=com.myapp.topic1, match=exact
publishing test events ..
event: args= [ 'hello subscriber!', 1 ] , kwargs= {}
subscription: sub_topic= com.myapp.topic1 , sub_match= exact , session_ident= E
received 1 events up to this point ..
event: args= [ 'hello subscriber!', 1 ] , kwargs= {}
subscription: sub_topic= com.myapp , sub_match= prefix , session_ident= C
received 2 events up to this point ..
event: args= [ 'hello subscriber!', 1 ] , kwargs= {}
subscription: sub_topic= com..topic1 , sub_match= wildcard , session_ident= B
received 3 events up to this point ..
event: args= [ 'hello subscriber!', 1 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
received 4 events up to this point ..
event: args= [ 'hello subscriber!', 2 ] , kwargs= {}
subscription: sub_topic= com.myapp , sub_match= prefix , session_ident= C
received 5 events up to this point ..
event: args= [ 'hello subscriber!', 2 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
received 6 events up to this point ..
event: args= [ 'hello subscriber!', 3 ] , kwargs= {}
subscription: sub_topic= com.myapp , sub_match= prefix , session_ident= C
received 7 events up to this point ..
event: args= [ 'hello subscriber!', 3 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
received 8 events up to this point ..
all test events published!
event: args= [ 'hello subscriber!', 5 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
closing ..
✖ testPubsubMultipleMatchingSubs

Assertion Message: 
Expected:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



Got:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



AssertionError: false == true
Expected:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



Got:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



    at Object.ok (/home/om26er/code/crossbario/autobahn-js/node_modules/nodeunit/lib/types.js:83:39)
    at Subscription.on_event [as handler] (/home/om26er/code/crossbario/autobahn-js/test/test_pubsub_multiple_matching_subs.js:93:25)
    at Object.Session.self._process_EVENT (/home/om26er/code/crossbario/autobahn-js/lib/session.js:526:20)
    at Object.Session.self._socket.onmessage (/home/om26er/code/crossbario/autobahn-js/lib/session.js:1013:46)
    at WebSocket.<anonymous> (/home/om26er/code/crossbario/autobahn-js/lib/transport/websocket.js:197:23)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:442:20)
    at Receiver.receiverOnMessage (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/websocket.js:719:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.EventEmitter.emit (domain.js:442:20)
    at Receiver.dataMessage (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/receiver.js:414:14)
    at perMessageDeflate.decompress (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/receiver.js:371:23)
    at _decompress (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/permessage-deflate.js:307:9)
    at _inflate.flush (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/permessage-deflate.js:389:7)
    at afterWrite (_stream_writable.js:480:3)
    at onwrite (_stream_writable.js:471:7)


test.js
(node:6089) TimeoutOverflowWarning: 1.0000000000000002e+31 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:6089) TimeoutOverflowWarning: 1.0000000000000002e+31 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:6089) TimeoutOverflowWarning: 1.0000000000000002e+31 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:6089) TimeoutOverflowWarning: 1.0000000000000002e+31 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:6089) TimeoutOverflowWarning: 1.0000000000000002e+31 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
CLOSE closed { reason: 'wamp.close.normal',
  message: '',
  retry_delay: null,
  retry_count: null,
  will_retry: false }
CLOSE closed { reason: 'wamp.close.normal',
  message: '',
  retry_delay: null,
  retry_count: null,
  will_retry: false }
CLOSE closed { reason: 'wamp.close.normal',
  message: '',
  retry_delay: null,
  retry_count: null,
  will_retry: false }
CLOSE closed { reason: 'wamp.close.normal',
  message: '',
  retry_delay: null,
  retry_count: null,
  will_retry: false }
CLOSE closed { reason: 'wamp.close.normal',
  message: '',
  retry_delay: null,
  retry_count: null,
  will_retry: false }
all sessions connected
all test sessions subscribed!
session_ident=B subscribed with topic=com..topic1, match=wildcard
session_ident=C subscribed with topic=com.myapp, match=prefix
session_ident=D subscribed with topic=com, match=prefix
session_ident=E subscribed with topic=com.myapp.topic1, match=exact
publishing test events ..
event: args= [ 'hello subscriber!', 1 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
received 1 events up to this point ..
event: args= [ 'hello subscriber!', 1 ] , kwargs= {}
subscription: sub_topic= com..topic1 , sub_match= wildcard , session_ident= B
received 2 events up to this point ..
event: args= [ 'hello subscriber!', 1 ] , kwargs= {}
subscription: sub_topic= com.myapp , sub_match= prefix , session_ident= C
received 3 events up to this point ..
event: args= [ 'hello subscriber!', 1 ] , kwargs= {}
subscription: sub_topic= com.myapp.topic1 , sub_match= exact , session_ident= E
received 4 events up to this point ..
event: args= [ 'hello subscriber!', 2 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
received 5 events up to this point ..
event: args= [ 'hello subscriber!', 2 ] , kwargs= {}
subscription: sub_topic= com.myapp , sub_match= prefix , session_ident= C
received 6 events up to this point ..
event: args= [ 'hello subscriber!', 3 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
received 7 events up to this point ..
event: args= [ 'hello subscriber!', 3 ] , kwargs= {}
subscription: sub_topic= com.myapp , sub_match= prefix , session_ident= C
received 8 events up to this point ..
all test events published!
event: args= [ 'hello subscriber!', 5 ] , kwargs= {}
subscription: sub_topic= com , sub_match= prefix , session_ident= D
closing ..
✖ testPubsubMultipleMatchingSubs

Assertion Message: 
Expected:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



Got:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



AssertionError: false == true
Expected:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



Got:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



    at Object.ok (/home/om26er/code/crossbario/autobahn-js/node_modules/nodeunit/lib/types.js:83:39)
    at Subscription.on_event [as handler] (/home/om26er/code/crossbario/autobahn-js/test/test_pubsub_multiple_matching_subs.js:93:25)
    at Object.Session.self._process_EVENT (/home/om26er/code/crossbario/autobahn-js/lib/session.js:526:20)
    at Object.Session.self._socket.onmessage (/home/om26er/code/crossbario/autobahn-js/lib/session.js:1013:46)
    at WebSocket.<anonymous> (/home/om26er/code/crossbario/autobahn-js/lib/transport/websocket.js:197:23)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:442:20)
    at Receiver.receiverOnMessage (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/websocket.js:719:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.EventEmitter.emit (domain.js:442:20)
    at Receiver.dataMessage (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/receiver.js:414:14)
    at perMessageDeflate.decompress (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/receiver.js:371:23)
    at _decompress (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/permessage-deflate.js:307:9)
    at _inflate.flush (/home/om26er/code/crossbario/autobahn-js/node_modules/ws/lib/permessage-deflate.js:389:7)
    at afterWrite (_stream_writable.js:480:3)
    at onwrite (_stream_writable.js:471:7)


FAILURES: 2/2 assertions failed (5139ms)
npm ERR! Test failed.  See above for more details.
```

**Comment by oberstet** [comment]
it might be that the unit test is itself at error here .. the difference is just the order of events in case of multiple matching subs (and the WAMP spec does not guarantee ordering relations in that case):

```
Expected:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."



Got:

0 "all sessions connected"
1 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
2 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
3 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
4 "subscription: sub_topic=" "com..topic1" ", sub_match=" "wildcard" ", session_ident=" "B"
5 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
6 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
7 "event: args=" ["hello subscriber!",1] ", kwargs=" {}
8 "subscription: sub_topic=" "com.myapp.topic1" ", sub_match=" "exact" ", session_ident=" "E"
9 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
10 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
11 "event: args=" ["hello subscriber!",2] ", kwargs=" {}
12 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
13 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
14 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
15 "event: args=" ["hello subscriber!",3] ", kwargs=" {}
16 "subscription: sub_topic=" "com.myapp" ", sub_match=" "prefix" ", session_ident=" "C"
17 "event: args=" ["hello subscriber!",5] ", kwargs=" {}
18 "subscription: sub_topic=" "com" ", sub_match=" "prefix" ", session_ident=" "D"
19 "closing .."
```

**Comment by oberstet** [comment]
closing in favor of #408
