### ISSUE TITLE
bufferutil native build fails for Docker image baking

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#392]
```
npm info lifecycle bufferutil@4.0.0~install: bufferutil@4.0.0

> bufferutil@4.0.0 install /usr/local/lib/node_modules/autobahn/node_modules/bufferutil
> node-gyp-build

gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.2 | linux | arm64
gyp http GET https://nodejs.org/download/release/v7.7.2/node-v7.7.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v7.7.2/node-v7.7.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v7.7.2/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v7.7.2/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/autobahn/node_modules/bufferutil/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/.node-gyp/7.7.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/app/.node-gyp/7.7.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/autobahn/node_modules/bufferutil',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/usr/local/lib/node_modules/autobahn/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.c:2:22: fatal error: node_api.h: No such file or directory
 #include <node_api.h>
                      ^
compilation terminated.
bufferutil.target.mk:92: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/autobahn/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/autobahn/node_modules/bufferutil
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm info lifecycle bufferutil@4.0.0~install: Failed to exec install script
```

**Comment by oberstet** [comment]
this is fixed, the library builds fine using our docker toolchain image, see https://github.com/crossbario/autobahn-js/issues/409
