### ISSUE TITLE
Latest version fails with "Cannot find module 'debug'"

### ISSUE THREAD

**Issue by vdiez** [crossbario/autobahn-js#442]
```
 Cannot find module 'debug' { Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\www\projects\autoclean\node_modules\truffle-contract\lib\contract.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3) code: 'MODULE_NOT_FOUND' }
```

Seems this comes from dependency truffle-contract, which has "debug" declared as a dev dependency.

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/autobahn-js/pull/453
