### ISSUE TITLE
Docker armhf build problem

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#475]
Running

```
~/scm/crossbario/autobahn-js/docker$ make build-armhf
```

leads to

```Step 21/24 : RUN npm install -g --unsafe-perm autobahn-xbr@${AUTOBAHN_JS_XBR_VERSION}
 ---> Running in 60af69a1baa7
qemu: Unsupported syscall: 389
qemu: Unsupported syscall: 397
Unknown host QEMU_IFLA type: 47
Unknown host QEMU_IFLA type: 48
Unknown host QEMU_IFLA type: 43
Unknown host QEMU_IFLA type: 47
Unknown host QEMU_IFLA type: 48
Unknown host QEMU_IFLA type: 43
npm WARN deprecated truffle-contract@4.0.31: WARNING: This package has been renamed to @truffle/contract.
npm WARN deprecated truffle-interface-adapter@0.2.5: WARNING: This package has been renamed to @truffle/interface-adapter.

> sha3@1.2.3 install /usr/lib/node_modules/autobahn-xbr/node_modules/keccakjs/node_modules/sha3
> node-gyp rebuild

qemu: Unsupported syscall: 389
qemu: Unsupported syscall: 397
qemu: Unsupported syscall: 389
qemu: Unsupported syscall: 397
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-64-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/autobahn-xbr/node_modules/keccakjs/node_modules/sha3
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2019-10-02T19_27_21_618Z-debug.log
The command '/bin/sh -c npm install -g --unsafe-perm autobahn-xbr@${AUTOBAHN_JS_XBR_VERSION}' returned a non-zero code: 1
Command exited with non-zero status 1
0.08user 0.05system 5:47.62elapsed 0%CPU (0avgtext+0avgdata 64448maxresident)k
2728inputs+0outputs (11major+8856minor)pagefaults 0swaps
Makefile:29: recipe for target 'build_alpine' failed
make[1]: *** [build_alpine] Error 1
make[1]: Verzeichnis „/home/oberstet/scm/crossbario/autobahn-js/docker/armhf“ wird verlassen
Makefile:19: recipe for target 'build-armhf' failed
make: *** [build-armhf] Error 2
```

**Comment by om26er** [comment]
fixed via https://github.com/crossbario/autobahn-js/pull/480
