### ISSUE TITLE
Subprotocol error when creating connection with ws@8.0.0

### ISSUE THREAD

**Issue by benthepoet** [crossbario/autobahn-js#550]
The `8.0.0` version of `ws` introduced some breaking changes around protocols. Attempting to create a connection with this version yields the following error.

```js
could not create WAMP transport 'websocket':  SyntaxError: An invalid or duplicated subprotocol was specified
    at initAsClient (C:\Users\BenHanna\source\repos\wamp\node_modules\ws\lib\websocket.js:677:15)
    at new WebSocket (C:\Users\BenHanna\source\repos\wamp\node_modules\ws\lib\websocket.js:80:7)
    at C:\Users\BenHanna\source\repos\wamp\node_modules\autobahn\lib\transport\websocket.js:200:22
    at Factory.create (C:\Users\BenHanna\source\repos\wamp\node_modules\autobahn\lib\transport\websocket.js:288:9)
    at Connection._create_transport (C:\Users\BenHanna\source\repos\wamp\node_modules\autobahn\lib\connection.js:112:44)
    at retry (C:\Users\BenHanna\source\repos\wamp\node_modules\autobahn\lib\connection.js:249:33)
    at Connection.open (C:\Users\BenHanna\source\repos\wamp\node_modules\autobahn\lib\connection.js:383:4)
    at Object.<anonymous> (C:\Users\BenHanna\source\repos\wamp\index.js:65:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
could not create any WAMP transport
```

**Comment by vnktswrl** [comment]
Using >= instead of default ^ in the package.json file is causing the problem. A major version of ws module is getting installed, and it is breaking the autobahn module.
Why are we using >= in package.json? Is there a reason?

**Comment by vnktswrl** [comment]
I see. You are supporting from ws v1.0.

**Comment by vnktswrl** [comment]
Can you put an upper limit to the dependency module versions so that they don't break autobahn in future.
https://semver.npmjs.com/

**Comment by iamciroja** [comment]
Hello, everyone! Are there any good news on this issue? :)

**Comment by gvatsov** [comment]
I used `npm-force-resolutions` for my project as a workaround for this issue.

**Comment by DamiToma** [comment]
I'm not sure what the state of this issue is, but I tested with `ws v8.6.0` and the reason it's erroring is that there's a [regex test failing](https://github.com/websockets/ws/blob/ba214d96939737304fb76f662700e9df01bb4418/lib/websocket.js#L739). Autobahn passes both JSON and webpack serialization split by a comma, but `ws` is expecting an array.

I removed [the join statement](https://github.com/crossbario/autobahn-js/blob/bd250753432a7bc61b7b7dae1df5fc70ddedcad6/packages/autobahn/lib/transport/websocket.js#L169) to pass an array and it's working beautifully now. Does it make sense to migrate to v8 and remove that?

**Comment by luixo** [comment]
@oberstet
It seems like you're maintaining the repository
The small change (removing the `join` and upgrading to the new ws version) can make users' lifes better. If that's too much - the condition may be added to check `ws` version before joining protocols.
We already have a PR for a quick fix: https://github.com/crossbario/autobahn-js/pull/552, I can create a PR for a proper one.

**Comment by DamiToma** [comment]
@oberstet I would suggest to also update the README, as it can be misleading for newbies. Initially I thought it supported up to version 2, we can probably get rid of the comment for Node V4.5.0 (I guess no one has been using that for years).
