### ISSUE TITLE
Connections failed on SSL

### ISSUE THREAD

**Issue by alexolliveira** [crossbario/autobahn-js#554]
Hello for everyone.
Even using 0.0.0.0, even using wss://, the websocket shows me a error:' WebSocket connection to 'wss://0.0.0.0:8081/' failed.
Error on line on Autobahn.js: self._websocket = new WebSocket(self._wsuri, [ab._subprotocol]);
Help me please.

**Comment by om26er** [comment]
use `ws` instrad of `wss`. I am pretty sure you dont have a certificate for 0.0.0.0

**Comment by alexolliveira** [comment]
I'm using ssl on my page. But  even with https, it does not work. 

The page at 'https://mysite.app/test.htm' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://machineip:8080/'. This request has been blocked; this endpoint must be available over WSS.
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
at new ab.Session (https://mysite.app/static/js/autobahn.js:341:26)

But when i connect using the wss:// protocol, an error is showed:
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
at new ab.Session (https://mysite.app/static/js/autobahn.js:341:26)

**Comment by alexolliveira** [comment]
@om26er 
I'm using SSL on my page. But even with https, it doesn't work.

A page at 'https://mysite.app/test.htm' was loaded over HTTPS but tried to connect to the insecure WebSocket endpoint 'ws: // machineip: 8080 /'. This request has been blocked; this terminal must be available in WSS.
Failed to build 'WebSocket': An insecure WebSocket connection cannot be found from a page loaded over HTTPS.
in the new ab.Session (https://mysite.app/static/js/autobahn.js:341:26)

But when I connect using the wss: // protocol, an error is set:
Failed to build 'WebSocket': An insecure WebSocket connection cannot be found from a page loaded over HTTPS.
in the new ab.Session (https://mysite.app/static/js/autobahn.js:341:26)
